2023-01-12 08:43:56   Arguments: Namespace(aggregation='gem', backbone='resnet18conv4', brightness=0, cache_refresh_rate=1000, contrast=0, criterion='triplet', dataset_name='tokyo_night', datasets_folder='/content/drive/MyDrive/MLDL/datasets_vg', device='cuda', efficient_ram_testing=False, epochs_num=1000, fc_output_dim=None, freeze_te=None, horizontal_flip=False, hue=0, infer_batch_size=16, l2='before_pool', lr=1e-05, lr_crn_layer=0.005, lr_crn_net=0.0005, majority_weight=0.01, margin=0.1, mining='partial', neg_samples_num=1000, negs_num_per_query=10, netvlad_clusters=64, num_workers=8, off_the_shelf='imagenet', optim='adam', patience=3, pca_dataset_folder=None, pca_dim=None, pretrain='imagenet', queries_per_epoch=5000, rand_perspective=0, random_resized_crop=0, random_rotation=0, recall_values=[1, 5, 10, 20], resize=[480, 640], resume='/content/drive/MyDrive/MLDL/results/base_gem/2023-01-06_11-10-32/best_model.pth', saturation=0, save_dir='/content/drive/MyDrive/MLDL/results/base_gem/resume_and_eval/tokyo_night/2023-01-12_08-43-56', seed=0, test_method='hard_resize', train_batch_size=4, train_positives_dist_threshold=10, trunc_te=None, val_positive_dist_threshold=25)
2023-01-12 08:43:56   The outputs are being saved in /content/drive/MyDrive/MLDL/results/base_gem/resume_and_eval/tokyo_night/2023-01-12_08-43-56
2023-01-12 08:43:58   Resuming model from /content/drive/MyDrive/MLDL/results/base_gem/2023-01-06_11-10-32/best_model.pth
2023-01-12 08:43:58   
Traceback (most recent call last):
  File "eval.py", line 102, in <module>
    test_ds = datasets_ws.BaseDataset(args, args.datasets_folder, args.dataset_name, "test")
  File "/content/drive/MyDrive/MLDL/deep-visual-geo-localization-benchmark-main/datasets_ws.py", line 75, in __init__
    raise FileNotFoundError(f"Folder {self.dataset_folder} does not exist")
FileNotFoundError: Folder /content/drive/MyDrive/MLDL/datasets_vg/tokyo_night/images/test does not exist

